# Generated by Django 3.0.7 on 2020-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200623_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='asana_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
