# Generated by Django 3.0.7 on 2020-06-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_asana_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
