# Generated by Django 3.0.7 on 2020-06-23 07:08

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tasks', '0003_auto_20200623_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='profiles.Profile'),
        ),
    ]
